project:
  type: website
  output-dir: docs

website:
  title: "Sara Acevedo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - now.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



